# Fill Story Workflow Configuration
name: "fill-story"
version: "1.0.0"
description: "Analyzes project documentation and story context to intelligently fill story files with complete technical specifications using BMAD agents"
author: "BMad"

# Critical variables
config_source: "{project-root}/.bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Module path and component files
installed_path: "{project-root}/.bmad/bmm/workflows/fill-story"
instructions: "{installed_path}/instructions.md"

# Input configuration
story_file: "{{user_provided_story_path}}"
project_context: "{project-root}/docs/project-context.md"
project_materials: "{project-root}/docs/project-materials"

standalone: true
